services:
  db:
    image: postgres:15.1-bullseye
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: bahn_alarm
  redis:
    image: redis:7.0.7
    ports:
    - 127.0.0.1:6379:6379